debug: true
spring:
  jpa:
    database: h2
    show-sql: true
    hibernate.ddl-auto: create-drop

---
spring:
  profiles: docker
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/gap
    username: test
    password: test

