version: '3.3'

services:
    gap_postgres:
      container_name: gap_postgres
      image: postgres:latest
      volumes:
        - db_data:/var/lib/postgresql/data
      restart: always
      expose: 
        - 5432
      ports: 
        - 5432:5432
      environment: 
        POSTGRES_ROOT: testroot
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_DB: gap
    gap_service:
      container_name: gap_service
      build:
        context: gap-service/
        dockerfile: Dockerfile
      image: gap_service:latest
      environment: 
        DB_HOST: gap_postgres
        SPRING_PROFILES_ACTIVE: docker
      depends_on: 
        - gap_postgres
      expose: 
        - 8080
      ports:
        - 8080:8080
    nginx:
      image: nginx:alpine
      container_name: nginx
      restart: unless-stopped
      tty: true
      expose:
        - 80
      ports:
        - "8081:80"
      volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./ui:/ui/
volumes:
    db_data:
